### ISSUE TITLE
rails g angularjs:install fails

### ISSUE THREAD

**Issue by et** [patcito/angularjs_scaffold#15]
`~/c/angularjs_rails_resource ❯❯❯ rails -v`

```
Rails 3.2.12
```

`~/c/angularjs_rails_resource ❯❯❯ rails g angularjs:install`

```
[WARNING] Could not load generator "generators/angularjs/install/install_generator". Error: uninitialized constant Angularjs::Rails::Generators.
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/angularjs_scaffold-0.0.24/lib/generators/angularjs/install/install_generator.rb:2:in `<module:Angularjs>'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/angularjs_scaffold-0.0.24/lib/generators/angularjs/install/install_generator.rb:1:in `<top (required)>'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:300:in `block (2 levels) in lookup'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:296:in `each'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:296:in `block in lookup'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:295:in `each'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:295:in `lookup'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:152:in `find_by_namespace'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/generators.rb:169:in `invoke'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands/generate.rb:12:in `<top (required)>'
/Users/et/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands.rb:29:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
Could not find generator angularjs:install.
```

The scaffold generator works fine though.

**Comment by EdJones** [comment]
What do I need to do to get this working?

And should I?

**Comment by EdJones** [comment]
Tried putting gem into gemfile, but the scaffold generator produced:

C:\Users\Ed\webapps\credit>rails g angularjs:scaffold Quests
      remove  app/assets/stylesheets/scaffolds.css.scss
      insert  app/assets/javascripts/routes.coffee.erb
C:/Ruby193/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/actions/inject_into_file.rb:99:in `binread': No such file or directory - C:/Users/Ed/webapps/credit/app/assets/javascripts/routes.coffee.erb (Errno::ENOENT)
